baseURL = "https://uxconsulting-41d0e.web.app"
languageCode = "en-us"
title = "Eldr Media Blog"
theme = "designsystem"

# render unsafe html
[markup.goldmark.renderer]
unsafe= true
[markup.highlight.highlight]
noClasses= false
[markup.tableOfContents]
startLevel=   2
endLevel=         3

# hugo outputs
[outputs]
home = [ "HTML", "RSS", "JSON"]


[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/highlight/styles/github.css"
[[params.plugins.css]]
link = "plugins/fontawesome/fontawesome-pro/css/all.min.css"


[[params.plugins.js]]
link = "/plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
[[params.plugins.js]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"
[[params.plugins.js]]
link = "plugins/highlight/highlight.pack.js"
[[params.plugins.js]]
link = "/js/roll20.js"