baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"


# render unsafe html
[markup.goldmark.renderer]
unsafe= true
[markup.highlight.highlight]
noClasses= false
[markup.tableOfContents]
startLevel=   2
endLevel=         3